name: Docker Image CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{secrets.DOCKER_USER}}
      DOCKER_PASS: ${{secrets.DOCKER_PASSWORD}}
      NODE_DOCKER_PORT: ${{secrets.NODE_DOCKER_PORT}},
      MYSQLDB_USER: ${{secrets.MYSQLDB_USER}},
      MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}},
      MYSQLDB_DATABASE: ${{secrets.MYSQLDB_DATABASE}},
      MYSQLDB_DOCKER_PORT: ${{secrets.MYSQLDB_DOCKER_PORT}},
      MYSQLDB_LOCAL_PORT: ${{secrets.MYSQLDB_LOCAL_PORT}},
    
    steps:
    - name: Login to DockerHub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS

    - uses: actions/checkout@v3
    - name: Build the Docker images
      run: docker compose up -d 

    - name: Run tests
      run: docker-compose run test